#!/bin/bash

servers=(andromeda apollo euclid centauri aws lightsail ontheboard)
for server in ${servers[@]}
do
    echo -e "\n[+] Connecting to $server..."
    ssh -o ConnectTimeout=5 -t $server "~/bin/update-server"
done
