echo "\n[+] Connecting to andromeda..."
ssh -t andromeda "./update.sh"
echo "\n[+] Connecting to apollo..."
ssh -t apollo "./update.sh"
echo "\n[+] Connecting to pythagoras..."
ssh -t pythagoras "./update.sh"
